package com.aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "student")
public class Student {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String studentId;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;
}
